name: Build package and run tests
on:
  workflow_dispatch:
    branches: "*"
  push:
    branches: "*"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Install poetry
        uses: snok/install-poetry@v1.4.2
      - run: poetry -P build-tool install
      - run: poetry -P build-tool run pytest
